// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelvetVeogue.Data;

#nullable disable

namespace VelvetVeogue.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VelvetVeogue.Models.TblContactUS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Tbl_ContactUS");
                });

            modelBuilder.Entity("VelvetVeogue.Models.TblLogin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("TblLogins");
                });

            modelBuilder.Entity("VelvetVeogue.Models.Tbl_CompleteOrders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CVCNO")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CardNo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cardDate")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("contactNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("date")
                        .HasColumnType("DateTime");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("img")
                        .IsRequired()
                        .HasColumnType("varbinary");

                    b.Property<decimal>("price")
                        .HasColumnType("money");

                    b.Property<string>("sizes")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("Tbl_CompleteOrders");
                });

            modelBuilder.Entity("VelvetVeogue.Models.Tbl_Inquiries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNo")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Inquiries");
                });

            modelBuilder.Entity("VelvetVeogue.Models.Tbl_ItemDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQty")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<byte[]>("img")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_ItemDetails");
                });

            modelBuilder.Entity("VelvetVeogue.Models.Tbl_OrderDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CVCNO")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CardNo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cardDate")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("contactNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("date")
                        .HasColumnType("DateTime");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("img")
                        .IsRequired()
                        .HasColumnType("varbinary");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<decimal>("price")
                        .HasColumnType("money");

                    b.Property<string>("sizes")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("Tbl_OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
